### ISSUE TITLE
New Elevator entity

### ISSUE THREAD

**Issue by k00ni** [sozialhelden/a11yjson#6] opened 2019-04-25 08:33 UTC
I had a hard time finding information about elevator modelling in your specification. This is the only information i could find:

https://github.com/sozialhelden/ac-format/search?q=elevator&unscoped_q=elevator

I guess there is no more information about it yet?

---

I would propose an entity `Elevator` which has the following properties:

| Property                                 | Data Type      |
|:-----------------------------------------|:---------------|
| **isAccessibleWithWheelchair**               | bool|undefined |
| ~~doorWidth~~ see *Door*                                | Length         |
| ~~spaceWidth~~ see *cabinWidth*                               | Length         |
| ~~spaceDepth~~ see *cabinLength*                               | Length         |
| ~~inCabineDistanceFromGroundHighestButton~~ see `maximalHeightOfControls` | Length         |
| ~~outsideDistanceFromGroundHighestButton~~ see `maximalHeightOfControls`   | Length         |
| **maximalHeightOfControls** (in- and outside) | Length |
| ~~turningCircleOnExit~~ see *Door*                  | number         |
| ~~numberOfStepsTillElevator~~ see *Stairs* | number |

*Feel free to adapt the properties, if there is a more suitable word in English.*

**Status**: clarified

**Comment by opyh** [comment] 2019-04-25 17:03
Thanks for the feedback! For elevators, escalators and other equipment/facilities inside/around places there is an entity called `EquipmentInfo`. An `EquipmentInfo` has [`EquipmentProperties`](https://github.com/sozialhelden/ac-format/blob/a353d5f7fd24a9cc579997e659a11ead8f37c05a/src/EquipmentProperties.ts) – that's where you find most of the properties you want. Currently we have the control height in one attribute. `EquipmentProperties` can also include information about a [`Door`](https://github.com/sozialhelden/ac-format/blob/a353d5f7fd24a9cc579997e659a11ead8f37c05a/src/Door.ts), which is how you would model turning space in front etc.

**Comment by k00ni** [comment] 2019-04-26 12:54
Thanks for the info. Using `EquipmentInfo` as some kind of a proxy for `EquipmentProperties` seems weird to me. I guess the approach behind ac-format is to model individual instances of objects rather than attaching it all on one "thing", like an entrance. It adds more complexity to the data structures, but its more expressive.

So would you say that the following model is appropriate?

```
Place ---> EquipmentInfo ---> EquipmentProperties
                              [ = has elevator related information ] 
```
Which of these entities can i call "elevator"?

**Comment by opyh** [comment] 2019-04-28 22:55
I've left a comment about the geometry feature / properties separation here: https://github.com/sozialhelden/ac-format/issues/8#issuecomment-487422199.

Your model is appropriate. An elevator would be an `EquipmentInfo`. The elevator's attributes would belong in its `properties` attribute, and be of type `EquipmentProperties`. If the elevator belongs to a specific PoI, it would have a `placeInfoId` pointing to the ID attribute of an existing `PlaceInfo`.

**Comment by k00ni** [comment] 2019-04-29 07:30
Would do you mean with `Pol`?

I adapted the list of suggested new properties on top.

**Comment by opyh** [comment] 2019-04-29 12:09
PoI should mean 'Point of Interest', sorry :)

Here detail comments about the properties:
- `isAccessibleWithWheelchair`: Good idea. Even if other attributes are there, an elevator still might not be accessible for any non-modelable reason.
- `doorWidth`, `turningCircleOnExit` - this can already be modeled by adding a [`Door` as `door` property](https://github.com/sozialhelden/ac-format/blob/master/src/EquipmentProperties.ts#L106) to the elevator.
- `spaceWidth`, `spaceDepth` - exists already as `cabinWidth`/`cabinLength`: https://github.com/sozialhelden/ac-format/blob/master/src/EquipmentProperties.ts#L96
- `inCabineDistanceFromGroundHighestButton`: I'd not differentiate between inside and outside buttons. If you want to operate an elevator without assistance, what matters is the maximal height of _any_ controls that you need. It's a good idea to think about the difference though, so I'd rather rename our existing property `heightOfControls` to `maximalHeightOfControls` and clarify in the documentation what this means (and mention that if the inside controls are duplicated, the lower ones count): `https://github.com/sozialhelden/ac-format/blob/88c3e76e20f6d0314aedb8f7ffc35744d670d440/src/EquipmentProperties.ts#L91` to 
- `numberOfStepsTillElevator`: This is not so simple: An elevator can have multiple entrances at multiple sides on multiple building levels, which all would have to be modeled. We have to think this through in a bit more detail, especially balancing it with real-life effort of people who have to survey these data. I'd suggest to keep it simple and set the `isAccessibleWithWheelchair` attribute to `false` if there are steps, until we have a better overall model for 3D buildings.

**Comment by k00ni** [comment] 2019-05-02 07:38
I agree with your points and adapted the list on top accordingly. Renaming `inCabineDistanceFromGroundHighestButton` makes sense `maximalHeightOfControls`.

Regarding point 4: If the lower ones count, what if one needs to access the highest buttons? IMHO only mentioning the height of the lowest is misleading. Or maybe i misunderstood your point here:

> [..] and mention that if the inside controls are duplicated, the lower ones count [..]

**Comment by opyh** [comment] 2019-05-06 12:04
The lower ones would count only if they are an exact duplicate of the higher ones, which is the case in many public transit elevators where you have one vertical control panel and one horizontal, lower one.

![](https://www.weymann-aufzuege.de/fileadmin/user_upload/uploads_editorial_department/public/_Daten_AP/3_Aufzuege/3_2_Ausstattung/3_2_2_Tableaus/WEY_Aufzuege_Ausstattung_Tableaus_Bild03.jpg)

**Closed** 2021-10-04 13:27 UTC
